### ISSUE TITLE
Create file with aggregated phenotype data

### ISSUE THREAD

**Issue by kshefchek** [genophenoenvo/terraref-datasets#24]
In order to perform that gwas analysis we need all relevant phenotype data in a file.  Since I'm unsure of the final format, the tall format should work fine and I can convert it as needed.

**Comment by MagicMilly** [comment]
@kshefchek I shared the tall format trait table with you on [CyVerse](https://cyverse.org/discovery-environment) as a collaborator. Let me know if you aren't able to access it. I haven't done much with it since we aren't sure exactly what you need yet. The main issue is that some traits are measured multiple times in a day and sometimes divided into east and west subplots. If you need something like only one averaged value per day per plot, let me know. 

If needed, the trait-ontology mappings can be found on the [Google Drive](https://drive.google.com/drive/folders/1B9Hmj2Xwu0J9arTfhFiFZqkEktSeag63?usp=sharing) for now.

**Comment by kshefchek** [comment]
thanks!  I'll take a pass at using this file in the gwas file.  In terms of measured values, I'll have to defer to someone who has domain knowledge in this area or has a better sense of the analysis goals.

**Comment by MagicMilly** [comment]
Closing and creating new issue #26 for traits associated with E and W subplots and / or with duplicate timestamps
